### ISSUE TITLE
Issue 502

### ISSUE THREAD

**Issue by Iris-howest2019** [dave-the-scientist/miphy#3]
Hello,

I would really like to upload the following files, but I always get an error message:
"Error uploading files; the server returned code 502"

I cannot find the solution. (Tree was sent in Newick format)

Thanks in advance,
Student Iris

[Tree.txt](https://github.com/dave-the-scientist/miphy/files/3800578/Tree.txt)
[PGC_info.txt.txt](https://github.com/dave-the-scientist/miphy/files/3800579/PGC_info.txt.txt)

**Comment by dave-the-scientist** [comment]
Hello Iris,
I looked into it, and you were getting errors for 2 reasons: 1) because your species names from the info file have spaces in them ("Homo sapiens" should be "Homo_sapiens" in the species tree and in the species assignment) and 2) because your species tree is spread over a couple of lines. I've added a new error message to indicate that spaces are not allowed, and modified the code so that species trees can be separated like that. I'll try to get those changes up on the web version of the tool soon, but it might take me a couple of days.

I modified your info file so that it will work with the current web version of MIPhy. I also looked at your gene tree, and noticed it needed to be rooted (it's very difficult to interpret otherwise). I've included a rooted version of that tree for you, and you should be able to run your analysis with these new files.

However, I should also point out that MIPhy is designed for multi-copy gene families in several species. The program expects that most species will have multiple genes in the gene family, but it appears most of your species only have a single gene. It's difficult to say what impact this will have on the results, but I suspect they will be harder to interpret.

I hope this has helped!

[PGC_info.txt.txt](https://github.com/dave-the-scientist/miphy/files/3805261/PGC_info.txt.txt)
[Tree.txt](https://github.com/dave-the-scientist/miphy/files/3805265/Tree.txt)
